version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:8.11.1

    steps:
      - checkout
      - restore_cache:
          key: browser-extension-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install Chromium
          command: |
            apt update -q -y
            apt install -q -y chromium
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: browser-extension-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
