version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:8.11.1

    steps:
      - checkout
      - restore_cache:
          key: browser-extension-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install Google Chrome
          command: |
            wget --no-check-certificate https://dl-ssl.google.com/linux/linux_signing_key.pub
            sudo apt-key add linux_signing_key.pub
            echo "deb http://dl.google.com/linux/chrome/deb/ stable non-free main " >> /etc/apt/sources.list
            apt-get install google-chrome-stable -q -y
      - run:
          name: Install dependencies
          command: |
            yarn
            yarn add --force --dev phantomjs-prebuilt
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: browser-extension-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
